adb: Keep looping on `pidof` if it errors
Sometimes the app hasn't started yet, and `xbuild` fails with:

    Error: failed to get pid:

because `pidof` could not find any process with that name. Simply
running the loop again usually gets it to catch the `pid` the second
time.

Additionally running `am start` with `-W` flag didn't make a difference
towards blocking longer before the app/activity actually started.